#!/usr/bin/env python3
"""Copy catalog skills, the shared references they cite, and the agent templates into a project's .claude/ directory.

Never overwrites a file that already exists in the project: the project owns and adapts its copies.

Usage:
  setup_project.py install [--project DIR]                core skills, agents, AGENTS.md/CLAUDE.md, catalog index
  setup_project.py add SKILL [SKILL ...] [--project DIR]  catalog skills plus the skills and references they link to
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

CATALOG = Path(__file__).resolve().parents[3] / "catalog"
SKILLS = CATALOG / "skills"

SIBLING_SKILL = re.compile(r"\.\./([\w-]+)/SKILL\.md")
SHARED_REFERENCE = re.compile(r"\.\./\.\./references/([\w.-]+\.md)")


def catalog_skills() -> list[str]:
    return sorted(p.parent.name for p in SKILLS.glob("*/SKILL.md"))


def core_skills() -> list[str]:
    lines = (CATALOG / "core.txt").read_text(encoding="utf-8").splitlines()
    return [line.strip() for line in lines if line.strip() and not line.startswith("#")]


def description(name: str) -> str:
    text = (SKILLS / name / "SKILL.md").read_text(encoding="utf-8")
    match = re.search(r"^description:\s*(.+)$", text, re.MULTILINE)
    return match.group(1).strip().strip("'\"") if match else ""


def links(name: str) -> tuple[set[str], set[str]]:
    """Sibling skills and shared references a skill links to, so they travel with it."""
    text = "\n".join(f.read_text(encoding="utf-8") for f in (SKILLS / name).rglob("*.md"))
    return set(SIBLING_SKILL.findall(text)) - {name}, set(SHARED_REFERENCE.findall(text))


def with_dependencies(names: list[str]) -> list[str]:
    ordered: list[str] = []
    pending = list(names)
    while pending:
        name = pending.pop(0)
        if name not in ordered:
            ordered.append(name)
            pending.extend(sorted(links(name)[0]))
    return ordered


def copy(source: Path, target: Path, label: str, report: list[str]) -> None:
    if target.exists():
        report.append(f"kept      {label} (already in the project)")
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    if source.is_dir():
        shutil.copytree(source, target)
    else:
        shutil.copy2(source, target)
    report.append(f"added     {label}")


def install_skills(names: list[str], claude: Path, report: list[str]) -> None:
    # Several skills share a checklist; copy and report each one once.
    references: set[str] = set()
    for name in with_dependencies(names):
        copy(SKILLS / name, claude / "skills" / name, f"skills/{name}", report)
        references |= links(name)[1]
    for ref in sorted(references):
        copy(CATALOG / "references" / ref, claude / "references" / ref, f"references/{ref}", report)


def write_index(claude: Path) -> None:
    installed = {p.parent.name for p in (claude / "skills").glob("*/SKILL.md")}
    available = [name for name in catalog_skills() if name not in installed]
    lines = [
        "# Skill catalog",
        "",
        "Catalog skills **not installed** in this project. Generated by `setup-project`; do not edit.",
        "When a spec or plan needs one, suggest it to the owner and, if approved, add it with",
        "`/agent-skills:setup-project add <skill>` (requires the agent-skills plugin).",
        "",
    ]
    lines += [f"- `{name}`: {description(name)}" for name in available] or ["Every catalog skill is installed."]
    (claude / "catalog.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("command", choices=["install", "add"])
    parser.add_argument("skills", nargs="*")
    parser.add_argument("--project", type=Path, default=Path.cwd())
    args = parser.parse_args(argv)
    claude = args.project.resolve() / ".claude"
    report: list[str] = []

    if args.command == "install":
        if args.skills:
            parser.error("`install` takes no skill names; use `add`")
        install_skills(core_skills(), claude, report)
        for agent in sorted((CATALOG / "agents").glob("*.md")):
            copy(agent, claude / "agents" / agent.name, f"agents/{agent.name}", report)
        for template in ("AGENTS.md", "CLAUDE.md"):
            copy(CATALOG / "templates" / template, claude.parent / template, template, report)
    else:
        if not args.skills:
            parser.error("`add` needs at least one skill name")
        unknown = [name for name in args.skills if name not in catalog_skills()]
        if unknown:
            print(f"Unknown skill(s): {', '.join(unknown)}. See .claude/catalog.md.", file=sys.stderr)
            return 1
        install_skills(args.skills, claude, report)

    write_index(claude)
    print("\n".join(report + ["wrote     catalog.md"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
